defaults:
  - override hydra/launcher: submitit_slurm

hparams:
  device: "cuda"
  model: "microsoft/phi-1_5"
  question_start_tag: "Question: "
  question_end_tag: "\n"
  answer_tag: "Answer: "
  max_length: 256

  dataset: "full"

  training:
    seed: 0
    batch_size: 16
    gradient_accumulation_steps: 2
    learning_rate: 2e-5
    num_epochs: 5
    weight_decay: 0.01
    gradient_checkpointing: False

hydra:  
  sweep:
    dir: models/phi/
    subdir: ${hparams.training.seed}
  sweeper:
    params:
      hparams.training.seed: choice(0)

  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 120
    gres: gpu:1
    mem_gb: 80
    partition: gpu_a100
    qos: default
    cpus_per_task: 1
    tasks_per_node: 1
    name: spaceship
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    signal_delay_s: 0
    max_num_timeout: 0
